spring:
  config:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: myuser
    password: mypass
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/mywebserver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: "classpath:db/migration"
    validate-migration-naming: true
jwt:
  secret: mysecret
