spring:
  config:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: suhan1234
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/myapiserver?autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/local,classpath:db/callback
    validateMigrationNaming: true
redis:
  host: 127.0.0.1
  port: 6379
jwt:
  secret: mysecret
server:
  port: 8080