spring:
  profiles:
    active: dev
  config:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: suhan1234
    hikari:
      jdbc-url: jdbc:mysql://mysql:3306/myapiserver?autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    url: jdbc:mysql://mysql:3306/myapiserver?autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/local,classpath:db/callback
    validateMigrationNaming: true
redis:
  host: redis
  port: 6379
jwt:
  secret: mysecret
server:
  port: 8080
