services:
  mysql:
    image: mysql:8.0.39
    ports:
      - "4000:3306"
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      - ./db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: suhan1234
      MYSQL_DATABASE: myapiserver
  redis:
    image: redis:7.0
    ports:
      - "6380:6379"

