name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - uses: actions/checkout@v3

    # 2. Set up JDK 11
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # 3. Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x ./LuckyBikiDeffenceAPIServer/gradlew

    # 4. Build with Gradle (Use relative path to gradlew)
    - name: Build with Gradle
      run: ./LuckyBikiDeffenceAPIServer/gradlew clean build --no-daemon
